### ISSUE TITLE
Not existing dump function

### ISSUE THREAD

**Issue by eriklukiman** [iLexN/swoole-psr7#1]
in src/SwooleServerRequestConverter.php line 66 dump() function is not exist, so it caused error when used.

`PHP Fatal error:  Uncaught Error: Call to undefined function Ilex\SwoolePsr7\dump() in vendor/ilexn/swoole-convent-psr7/src/SwooleServerRequestConverter.php:66`

**Comment by iLexN** [comment]
Thank for your report. Already Fix
