### ISSUE TITLE
SameSite cookie attribute not sent.

### ISSUE THREAD

**Issue by evonicgu** [iLexN/swoole-psr7#20]
Hello, @iLexN. Firstly, I want to thank you for your great library, it solved my problem. Thank you very much. However, there is an issue with sending SameSite cookie attribute. I encountered this bug when trying to set cross-site cookies for my CORS requests. 
This is my code:

```PHP
$cookies = new SetCookies([SetCookie::create('Refresh-Token', $result[0]['refresh_token'])
            ->withHttpOnly()
            ->withSecure()
            ->withSameSite(SameSite::none())
            ->withExpires(Carbon::now()->add('1 month'))]);
```

I expected the SameSite attribute to be set to none, however it was unset. It seems to be an issue with your library, because there is no SameSite related functionality in `emitCookies()` method of `SwooleResponseConverter` class. A simple solution might be something like this:

```PHP
/**
     * Emit the cookies
     *
     * @param \Psr\Http\Message\ResponseInterface $response
     *
     * @return void
     */
    private function emitCookies(ResponseInterface $response): void
    {
        foreach (SetCookies::fromResponse($response)->getAll() as $cookie) {
            $this->swooleResponse->cookie(
                $cookie->getName(),
                $cookie->getValue(),
                $cookie->getExpires(),
                $cookie->getPath() ?? '/',
                $cookie->getDomain() ?? '',
                $cookie->getSecure(),
                $cookie->getHttpOnly(),
                substr($cookie->getSameSite()->asString(), 9) // using substr() because FigCookies returns a string that starts with SameSite=
            );
        }
    }
```

**Comment by iLexN** [comment]
Thank for provide the solution. Here is the fix #21, please try. only the different is the null check for `getSameSite()` before `->asString`

**Comment by evonicgu** [comment]
Oh, just forgot about the null check. I think it would be great to merge this PR into the master branch. I think I can close the issue now?

**Comment by iLexN** [comment]
tag 0.2.0
