### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by karbowiak** [iLexN/swoole-psr7#3]
Hello there!

i've been using your library for my own project for a while now, and while upgrading it to PHP8 i've run into the issue where Composer is complaining that this library in particular is limited to 7.2 or higher.

**Comment by iLexN** [comment]
Thanks for your report. Will spend some time take a look in the holiday.

**Comment by iLexN** [comment]
need wait dflydev/fig-cookies support PHP-8 (https://github.com/dflydev/dflydev-fig-cookies/pull/39)

**Comment by karbowiak** [comment]
@iLexN arh! crap i missed that - my apologies!

Time to whip out the `--ignore-platform-reqs` :D

Thanks for looking at it as quickly as you did tho <3

**Comment by iLexN** [comment]
Added PHP 8 support for v0.1.0
