### ISSUE TITLE
Package name typo?

### ISSUE THREAD

**Issue by programster** [iLexN/swoole-psr7#33]
Hey, 
Is the name of the package in the [composer.json file](https://github.com/iLexN/swoole-psr7/blob/master/composer.json) a typo?

![Selection_237](https://user-images.githubusercontent.com/5709838/124014516-86f1f080-d9db-11eb-86b3-07b5cc599497.png)

I would have thought it should be `convert` becase the package is useful for converting between swoole and psr7 message objects, but maybe there is another meaning to convent that I'm missing.

![Selection_238](https://user-images.githubusercontent.com/5709838/124014723-c8829b80-d9db-11eb-9a90-10b2ee25374b.png)

Thanks for the package though, really helped me get Swoole up with Slim 4.

**Comment by iLexN** [comment]
Thanks for report. It is a typo. let me research how to rename it and not break the exist user.

**Comment by programster** [comment]
I believe [this](https://stackoverflow.com/questions/55378780/how-to-rename-a-php-package-in-packagist) is the correct procedure (people will still be able to get the old code through the old name)

![Selection_240](https://user-images.githubusercontent.com/5709838/124246734-151fc100-db19-11eb-9660-0eaa0e63da0f.png)

**Comment by iLexN** [comment]
Yes. I already follow this step.

now when install the old package (typo one), will have a abandoned message.
```
 - Installing ilexn/swoole-convent-psr7 (0.2.0): Extracting archive
Package ilexn/swoole-convent-psr7 is abandoned, you should avoid using it. Use ilexn/swoole-convert-psr7 instead.
```

**Comment by programster** [comment]
Awesome, cheers :+1:
