### ISSUE TITLE
Warning in SwooleResponseConverter

### ISSUE THREAD

**Issue by evonicgu** [iLexN/swoole-psr7#80]
The warning itself is emitted by Swoole\Http\Response::write() method. If a response has empty body, but the Stream is not in eof state this code triggers the warning:

SwooleResponseConverter.php:86-99
```PHP
    /**
     * Emit the message body.
     *
     *
     */
    private function emitBody(ResponseInterface $response): void
    {
        $stream = $response->getBody();
        $stream->rewind();
        while (!$stream->eof()) {
            $this->response->write($stream->read(static::CHUNK_SIZE));
        }
        //$this->swooleResponse->end();
    }
```

I don't know why the stream does not have the eof state if it is empty. Maybe eof() return true only after an operation failing to get some bytes. The issue is solved if the loop is changed to this:

```PHP
        $data = $stream->read(static::CHUNK_SIZE);
        while ($data !== '') {
            $this->response->write($data);
            $data = $stream->read(static::CHUNK_SIZE);
        }
```

**Comment by evonicgu** [comment]
I couldn't find a more smart solution by myself, hope that you can think of something better looking than that code. However, it solves the issue and no more warning is triggered. By the way wanted to say a huge "thank you" for the project, it is a real time saver, that helps me every time dealing with swoole

**Comment by iLexN** [comment]
Thanks for your report. The fix is here #81 

Please help to test the branch.

```
composer require ilexn/swoole-convert-psr7:dev-fix-response-body
```

**Comment by evonicgu** [comment]
Sorry for late response. Will test the branch tomorrow, just need to upgrade to php8.1

**Comment by evonicgu** [comment]
Hello there, I've tested the change on  live webserver. Everything works s expected.

**Comment by iLexN** [comment]
Thanks, new tag 0.6.1 release
